/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_snail_snailffmpeg_live_LivePusher */

#ifndef _Included_com_snail_snailffmpeg_live_LivePusher
#define _Included_com_snail_snailffmpeg_live_LivePusher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_snail_snailffmpeg_live_LivePusher
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_snail_snailffmpeg_live_LivePusher_native_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_snail_snailffmpeg_live_LivePusher
 * Method:    native_start
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_snail_snailffmpeg_live_LivePusher_native_1start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_snail_snailffmpeg_live_LivePusher
 * Method:    native_setVideoCodecInfo
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_snail_snailffmpeg_live_LivePusher_native_1setVideoCodecInfo
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_snail_snailffmpeg_live_LivePusher
 * Method:    native_setAudioCodecInfo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_snail_snailffmpeg_live_LivePusher_native_1setAudioCodecInfo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_snail_snailffmpeg_live_LivePusher
 * Method:    getInputSamples
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_snail_snailffmpeg_live_LivePusher_getInputSamples
  (JNIEnv *, jobject);

/*
 * Class:     com_snail_snailffmpeg_live_LivePusher
 * Method:    native_pushAudio
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_snail_snailffmpeg_live_LivePusher_native_1pushAudio
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_snail_snailffmpeg_live_LivePusher
 * Method:    native_pushVideo
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_snail_snailffmpeg_live_LivePusher_native_1pushVideo
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_snail_snailffmpeg_live_LivePusher
 * Method:    native_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_snail_snailffmpeg_live_LivePusher_native_1stop
  (JNIEnv *, jobject);

/*
 * Class:     com_snail_snailffmpeg_live_LivePusher
 * Method:    native_release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_snail_snailffmpeg_live_LivePusher_native_1release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
